title: Welcome to Flexton
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "flexton.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Jaebong Jeong 
author-image:   1.jpg
author-job:     Computer Vision R&D Engineer
author-email:   jb.jeong07@gmail.com # Add your email for contant form.
author-twitter: jaebong_jeong # Add your twitter account
about-author:   I am a Computer Vision R&D Engineer at Playtag Inc. Always hungry to build a awsome AI system.

# Social settings
social-twitter:   jaebong_jeong
social-facebook:
social-github:    jbjeong 
social-pinterest: 
social-instagram: 
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: G-YJYFK1SQ9D # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
